name: Handle form submission and dispatch main workflow

on:
  workflow_dispatch:

jobs:
  send-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event to trigger main workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{
              "event_type": "run-provider-update",
              "client_payload": {
                "LeverancierEmail": "johan_tre@hotmail.com",
                "LeverancierNaam": "Voorbeeld Leverancier",
                "LeverancierStad": "Brussel",
                "LeverancierStraat": "Kerkstraat 12",
                "LeverancierPostadres": "Kerkstraat 12 1000 Brussel",
                "LeverancierKandidaat": "John Doe",
                "LeverancierOpgemaaktte": "Brussel",
                "LeverancierHoedanigheid": "Zaakvoerder",
                "LeverancierURLSignatureImage": "https://www.dropbox.com/scl/fi/novqnhqa68gimq5t1h03p/Akeem.jpg?rlkey=gvr2fbap4xfxf2yjm13hrd007&st=vktvu150&dl=1"
              }
            }'