name: Subscribe or Update provider

on:
  workflow_dispatch:
    inputs:
      LeverancierEmail:
        description: 'Leverancier Email'
        required: true
        type: string
      LeverancierNaam:
        description: 'Leverancier Naam'
        required: true
        type: string
      LeverancierStad:
        description: 'Leverancier Stad'
        required: true
        type: string
      LeverancierStraat:
        description: 'Leverancier Straat'
        required: true
        type: string
      LeverancierPostadres:
        description: 'Leverancier Postadres'
        required: true
        type: string
      LeverancierKandidaat:
        description: 'Leverancier Kandidaat'
        required: true
        type: string
      LeverancierOpgemaaktte:
        description: 'Leverancier Opgemaakt te'
        required: true
        type: string
      LeverancierHoedanigheid:
        type: choice
        description: 'Leverancier Hoedanigheid'
        required: true
        options:
          - Directe Freelancer
          - Eigen werknemer
          - Freelancer in onderaanneming
          - Subcontractor
      LeverancierURLSignatureImage:
        description: | 
          Leverancier URL Signature image -----------(supported: Dropbox, GoogleDrive, Uguu.se)
          💡Use https://bimi.dreamlead.be/signature-loader/ for assisted URL generation first.
          💡Check out /docs/signature-loader/README.md of this repo for more info.
        required: true
        type: string
      setLogLevelDebug:
        description: 'Enable DEBUG (Admin only)'
        required: false
        type: boolean

jobs:
  search_and_update_or_add_to_repo_and_db:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set custom log level
        id: set-log-level
        run: |
          if [[ "${{ github.actor }}" == "johantre" ]] && [[ "${{ github.event.inputs.setLogLevelDebug }}" == "true" ]]; then
            echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
          else
            echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
          fi

      - name: Check LOG_LEVEL in next step
        run: |
          echo "LOG_LEVEL in next step: $LOG_LEVEL"

      - name: Checkout executing Repository
        uses: actions/checkout@v3
        with:
          path: msword-properties-generator

      - name: Checkout msword-private-assets
        uses: actions/checkout@v3
        with:
          repository: johantre/msword-private-assets
          token: ${{ secrets.GH_PRIVATE_ASSETS_PAT }}
          path: msword-private-assets

      - name: Show folder structure for debugging
        run: |
          echo "📁 Current working directory: $(pwd)"
          echo "📂 Contents of workspace:"
          ls -lR /home/runner/work/msword-properties-generator

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cryptography-jproperties-pytz-gitpython-requests-google-auth-google-auth-oauthlib-google-auth-httplib2-google-api-python-client-dropbox-pillow
          restore-keys: |
            ${{ runner.os }}-pip-
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install Dependencies
        working-directory: msword-properties-generator
        run: |
          python -m pip install --upgrade pip
          pip install cryptography jproperties pytz gitpython requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client dropbox pillow

      - name: Encrypt and Populate SQLite Database
        env:
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          HASHING_KEY: ${{ secrets.HASHING_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          INPUT_LEVERANCIEREMAIL: ${{ github.event.inputs.LeverancierEmail }}
          INPUT_LEVERANCIERNAAM: ${{ github.event.inputs.LeverancierNaam }}
          INPUT_LEVERANCIERSTAD: ${{ github.event.inputs.LeverancierStad }}
          INPUT_LEVERANCIERSTRAAT: ${{ github.event.inputs.LeverancierStraat }}
          INPUT_LEVERANCIERPOSTADRES: ${{ github.event.inputs.LeverancierPostadres }}
          INPUT_LEVERANCIERKANDIDAAT: ${{ github.event.inputs.LeverancierKandidaat }}
          INPUT_LEVERANCIEROPGEMAAKTTE: ${{ github.event.inputs.LeverancierOpgemaaktte }}
          INPUT_LEVERANCIERHOEDANIGHEID: ${{ github.event.inputs.LeverancierHoedanigheid }}
          INPUT_LEVERANCIERURLSIGNATUREIMAGE: ${{ github.event.inputs.LeverancierURLSignatureImage }}
        working-directory: msword-properties-generator
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python src/msword_properties_generator/main/subscribe_or_update_provider.py

