name: Unsubscribe provider

on:
  workflow_dispatch:
    inputs:
      LeverancierEmail:
        description: 'Leverancier Email'
        required: true
        type: string
      setLogLevelDebug:
        description: 'Enable DEBUG (Admin only)'
        required: false
        type: boolean

jobs:
  search_and_remove_from_repo_and_db:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set custom log level
        run: |
          if [[ "${{ github.actor }}" == "johantre" ]] && [[ "${{ github.event.inputs.setLogLevelDebug }}" == "true" ]]; then
            echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
          else
            echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
          fi

      - name: Check LOG_LEVEL in next step
        run: |
          echo "env.LOG_LEVEL in next step: ${{ env.LOG_LEVEL }}"

      - name: Checkout executing Repository
        uses: actions/checkout@v3
        with:
          path: msword-properties-generator

      - name: Checkout msword-private-assets
        uses: actions/checkout@v3
        with:
          repository: johantre/msword-private-assets
          token: ${{ secrets.GH_PRIVATE_ASSETS_PAT }}
          path: msword-private-assets

      - name: Show folder structure for debugging
        run: |
          echo "📁 Current working directory: $(pwd)"
          echo "📂 Contents of workspace:"
          ls -lR /home/runner/work/msword-properties-generator

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cryptography-jproperties-pytz-gitpython-requests-google-auth-google-auth-oauthlib-google-auth-httplib2-google-api-python-client-dropbox-pillow
          restore-keys: |
            ${{ runner.os }}-pip-
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        working-directory: msword-properties-generator
        run: |
          python -m pip install --upgrade pip
          pip install cryptography jproperties pytz gitpython requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client dropbox pillow

      - name: Fetch SQLite Database and remove encrypted image
        env:
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          HASHING_KEY: ${{ secrets.HASHING_KEY }}
          INPUT_LEVERANCIEREMAIL: ${{ github.event.inputs.LeverancierEmail }}
        working-directory: msword-properties-generator
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python src/msword_properties_generator/main/unsubscribe_provider.py

