name: Unsubscribe provider

on:
  workflow_dispatch:
    inputs:
      LeverancierEmail:
        description: 'Leverancier Email'
        required: true
        type: string
      setLogLevelDebug:
        description: 'Enable DEBUG (Admin only)'
        required: false
        type: boolean

jobs:
  set-log-level:
    runs-on: ubuntu-latest
    steps:
      - name: Set custom log level
        run: |
          if [ "${{ github.event.inputs.setLogLevelDebug }}" == "true" ]; then
            echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
            echo the actor now is: "${{ github.actor }}"
          elif [[ "${ACTIONS_STEP_DEBUG}" == "true" ]] || [[ "${ACTIONS_RUNNER_DEBUG}" == "true" ]]); then
            echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
          else
            echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
          fi

  search_and_remove_from_repo_and_db:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cryptography-jproperties-pytz-gitpython-requests-google-auth-google-auth-oauthlib-google-auth-httplib2-google-api-python-client-dropbox-pillow
          restore-keys: |
            ${{ runner.os }}-pip-
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography jproperties pytz gitpython requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client dropbox pillow

      - name: Fetch SQLite Database and remove encrypted image
        env:
          LOG_LEVEL: INFO
          HASHING_KEY: ${{ secrets.HASHING_KEY }}
          INPUT_LEVERANCIEREMAIL: ${{ github.event.inputs.LeverancierEmail }}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python src/msword_properties_generator/main/unsubscribe_provider.py

